### ISSUE TITLE
It seems like users can only have on blog post

### ISSUE THREAD

**Issue by gossie** [Way-Maker7/weltLaender#38]
This sets the ID of the blog post to the ID of the user. That does not make sense. That way, when a user creates a post, the post will be created with the ID of the user as its own ID. When the same user wants to create a new post, the new post will overwrite the old one, because they have the same ID (the ID of the user).
https://github.com/Way-Maker7/weltLaender/blob/d5bff3d52d023d9e1f94cb09d90d05ca1dd0008a/backend/src/main/java/com/github/waymaker7/capstone/BlogsServices.java#L17

**Comment by Way-Maker7** [comment]
I have changed it. thank you!
